FROM node:22-alpine3.19

WORKDIR /app

COPY package.json .

ARG NODE_ENV
RUN if [ "$NODE_ENV" = "production" ] ; \
    then npm install --only=production ; \
    else npm install; \
    fi

# RUN npm install

COPY . .

# ENV PORT=4000

# EXPOSE $PORT

EXPOSE 4000

CMD ["npm", "run" ,"start-dev"]